
package fiap.scj.ws.soap.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MinhaSaudeImpl", targetNamespace = "http://soap.ws.scj.fiap/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MinhaSaudeImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculaImc", targetNamespace = "http://soap.ws.scj.fiap/", className = "fiap.scj.ws.soap.client.CalculaImc")
    @ResponseWrapper(localName = "calculaImcResponse", targetNamespace = "http://soap.ws.scj.fiap/", className = "fiap.scj.ws.soap.client.CalculaImcResponse")
    @Action(input = "http://soap.ws.scj.fiap/MinhaSaudeImpl/calculaImcRequest", output = "http://soap.ws.scj.fiap/MinhaSaudeImpl/calculaImcResponse")
    public int calculaImc(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "situacaoImc", targetNamespace = "http://soap.ws.scj.fiap/", className = "fiap.scj.ws.soap.client.SituacaoImc")
    @ResponseWrapper(localName = "situacaoImcResponse", targetNamespace = "http://soap.ws.scj.fiap/", className = "fiap.scj.ws.soap.client.SituacaoImcResponse")
    @Action(input = "http://soap.ws.scj.fiap/MinhaSaudeImpl/situacaoImcRequest", output = "http://soap.ws.scj.fiap/MinhaSaudeImpl/situacaoImcResponse")
    public String situacaoImc(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns fiap.scj.ws.soap.client.ResultadoImcDTO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "imc", targetNamespace = "http://soap.ws.scj.fiap/", className = "fiap.scj.ws.soap.client.Imc")
    @ResponseWrapper(localName = "imcResponse", targetNamespace = "http://soap.ws.scj.fiap/", className = "fiap.scj.ws.soap.client.ImcResponse")
    @Action(input = "http://soap.ws.scj.fiap/MinhaSaudeImpl/imcRequest", output = "http://soap.ws.scj.fiap/MinhaSaudeImpl/imcResponse")
    public ResultadoImcDTO imc(
        @WebParam(name = "arg0", targetNamespace = "")
        PessoaSaudeDTO arg0);

}
